name: Generate Lighthouse report

on:
  issue_comment:
    types: [created, edited]

jobs:
  generate_lighthouse_report:
    if: github.event_name == 'pull_request' && contains(github.event.comment.body, 'Visit Preview')
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: main

      - name: Capture Vercel preview URL
        id: vercel_preview_url
        uses: binary-com/vercel-preview-url-action@v1.0.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          preview_url_regexp: \[Visit Preview\]\((.*.app)\)

      - name: Generate Lighthouse report
        uses: treosh/lighthouse-ci-action@v9
        id: lighthouse_report
        with:
          # urls: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
          temporaryPublicStorage: true
          urls: "https://deriv-app-git-fork-adrienne-deriv-adrienne-deriv-task-78-14f3fe.binary.sx"
          uploadArtifacts: true
          # specify Lighthouse score assertions here
          configPath: ".github/lighthouse/lighthouserc.json"

      - name: Retrieve Lighthouse score
        id: lighthouse_score
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = ${{ steps.lighthouse_report.outputs.manifest }}[0].summary
            const links = ${{ steps.lighthouse_report.outputs.links }}

            const formatResult = (res) => Math.round((res * 100))
            Object.keys(result).forEach(key => result[key] = formatResult(result[key]))

            const score = res => res >= 90 ? '🟢' : res >= 50 ? '🟧' : '🔺'

            const comment = [
                `🚨 [Lighthouse report](${Object.values(links)[0]}) for the changes in this PR:`,
                '| Category | Score |',
                '| --- | --- |',
                `| ${score(result.performance)} Performance | ${result.performance} |`,
                `| ${score(result.accessibility)} Accessibility | ${result.accessibility} |`,
                `| ${score(result['best-practices'])} Best practices | ${result['best-practices']} |`,
                `| ${score(result.seo)} SEO | ${result.seo} |`,
                `| ${score(result.pwa)} PWA | ${result.pwa} |`,
                ' ',
                `*Lighthouse ran with [${Object.keys(links)[0]}](${Object.keys(links)[0]})*`
            ].join('\n')

             core.setOutput("comment", comment);

      - name: Posting Lighthouse report
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: Lighthouse report
          number: ${{github.event.issue.number}}
          message: ${{steps.lighthouse_score.outputs.comment}}
